POINTING_DEVICE_DRIVER = analog_joystick
# RGBLIGHT_ENABLE = yes
# WS2812_DRIVER_REQUIRED = yes
#
# QK_RGB_MATRIX_ON = yes
OS_DETECTION_ENABLE = yes
LEADER_ENABLE = yes
WPM_ENABLE = yes
COMMAND_ENABLE = no
TAP_DANCE_ENABLE = yes
SPACE_CADET_ENABLE   = yes
UNICODEMAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
CAPS_WORD_ENABLE = yes


SRC += lib/oled.c

